Hello Microverse Project Pull Request 2
sulaimonaa/Hello-Microverse pull request #1
Opened 2023-03-23 11:20 UTC by sulaimonaa

2023-03-23 12:56 UTC, DuaneDave requested changes
Hi @sulaimonaa👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Correct usage of github flow
✔️ The linters are correctly set up


## Required Changes ♻️
- It is important to have a pull request summary and not any summary goes, but a very detailed one that outlines the changes that has been made in this milestone, this will enable code reviewers to tell what you have succeeded in accomplishig in the PR. 
Please click one the icon i have highlighted red in the screenshot below to make edits to the summary.

![edit](https://user-images.githubusercontent.com/84930355/227202490-d0ca0775-1c7d-4e73-b5b6-71924e8cc784.PNG)
 Example of a good PR summary :

```
  - Added index,html file
  - Set up linters for the project
```
- Good job including a readme.md file in the repository. But currently, the readme is not properly written since there are important sections that were not added. Please add the recommended [Microverse](https://github.com/microverseinc/readme-template) readme template the way it was provided. All sections of this readme are important and should not be removed as you have done. The only section that is optional is the FAQ section. You can checkout this example of a good [readme](https://github.com/sunga12/My-Portfolio/tree/setup-mobile-first) 

- To follow best practices, ensure to write commit messages in the imperative tense. Instead of saying 'Made changes too the readme' you can say 'Make changes to the readme file'

_Check the comments under the review._

**NOTE : ** Ensure not to close this pull request or delete this repo to open another one before asking for another review. You should ask for review with the same PR every time.

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 12:56 UTC, DuaneDave commented on README.md
> +- License
Please remove every appearance of comments in the readme because it makes the documentation cluttered and less professional.

2023-03-23 12:56 UTC, DuaneDave commented on README.md
> +This project is [MIT](./LICENSE) licensed.
This link is expected to link to a file named LICENSE.md in your project structure but when it is clicked, it doesn't do that rather it redirect to a 404 page. Kindly add this file to your project structure in order to make the project set up more professional. You can checkout the details of this file [here](https://github.com/sunga12/My-Portfolio/blob/setup-mobile-first/LICENCE)

2023-03-23 12:56 UTC, DuaneDave commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
Please, remove this section of the readme because it was there initially to guide you in setting up a good readme.

2023-03-23 15:35 UTC, ghost approved these changes
Hi @sulaimonaa , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/11ISwbgCxEzMyY/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good documemntation👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 15:53 UTC, merged

2023-04-25 08:50 UTC, AlphaNtihinduka reviewed
# STATUS: APPROVED :green_circle: :clap: 
## Hi @sulaimonaa 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover: